#include "ad_sample.h"

void start_ad_data_upload(u32 length)
{
	AD_SAMPLE_mWriteReg(AD_SAMPLE_BASE_ADDR, AD_SAMPLE_CONTROL_REG, AD_SAMPLE_STOP_UPLOAD);
	AD_SAMPLE_mWriteReg(AD_SAMPLE_BASE_ADDR, AD_SAMPLE_DATA_LENGTH_REG, length);
	AD_SAMPLE_mWriteReg(AD_SAMPLE_BASE_ADDR, AD_SAMPLE_CONTROL_REG, AD_SAMPLE_START_UPLOAD);	// RISE EDGE TRIGGER
}


void stop_ad_data_upload()
{
	AD_SAMPLE_mWriteReg(AD_SAMPLE_BASE_ADDR, AD_SAMPLE_CONTROL_REG, AD_SAMPLE_STOP_UPLOAD);
}
